FROM rust:1.77 AS builder

WORKDIR /app

COPY Cargo*.toml ./
COPY src ./src

RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/app .

EXPOSE 8080

CMD ["./app"]
